# Generated by Django 3.0.4 on 2020-03-15 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smer',
            name='departman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ispitni_rokovi.Departman'),
        ),
    ]
