# Generated by Django 3.0.4 on 2020-03-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0003_auto_20200315_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='ispitnirok',
            name='predmet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ispitni_rokovi.Predmet'),
        ),
    ]
