# Generated by Django 3.0.4 on 2020-03-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0004_ispitnirok_predmet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smerpredmet',
            old_name='id_predmeta',
            new_name='predmet',
        ),
        migrations.RenameField(
            model_name='smerpredmet',
            old_name='id_smera',
            new_name='smer',
        ),
    ]
