# Generated by Django 3.0.4 on 2020-03-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0005_auto_20200315_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmerPredmet',
            new_name='VezaSmerPredmet',
        ),
    ]
