# Generated by Django 3.0.4 on 2020-03-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0006_auto_20200315_2153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vezasmerpredmet',
            unique_together={('smer', 'predmet')},
        ),
    ]
