# Generated by Django 3.0.4 on 2020-03-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0007_auto_20200315_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='vezasmerpredmet',
            name='godina_studija',
            field=models.IntegerField(default=1),
        ),
    ]
