# Generated by Django 3.0.4 on 2020-03-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0010_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
