# Generated by Django 3.0.4 on 2020-03-16 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0013_auto_20200316_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ispitnirok',
            name='url_slike',
        ),
        migrations.AddField(
            model_name='ispitnirok',
            name='slika',
            field=models.ImageField(default='', upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.IntegerField>/<django.db.models.fields.CharField>/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'bmp', 'jpeg', 'png'])]),
        ),
    ]
