# Generated by Django 3.0.4 on 2020-03-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0014_auto_20200316_2329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
