# Generated by Django 3.0.4 on 2020-03-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0015_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispitnirok',
            name='slika',
            field=models.ImageField(max_length=255, upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.IntegerField>/<django.db.models.fields.CharField>/'),
        ),
    ]
