# Generated by Django 3.0.4 on 2020-03-17 00:06

from django.db import migrations, models
import django.db.models.deletion
import ispitni_rokovi.models


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0016_auto_20200316_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispitnirok',
            name='slika',
            field=models.ImageField(max_length=255, upload_to=ispitni_rokovi.models.IspitniRok.putanjaSlike),
        ),
        migrations.CreateModel(
            name='Prijava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razlog_prijave', models.CharField(choices=[('a', 'Netacni podaci'), ('b', 'Pogresan datum ispitnog roka'), ('c', 'Neprimereni sadrzaj')], default='a', max_length=1)),
                ('dodatak', models.CharField(blank=True, max_length=512)),
                ('ispitni_rok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ispitni_rokovi.IspitniRok')),
            ],
        ),
    ]
