# Generated by Django 3.0.4 on 2020-03-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0017_auto_20200317_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijava',
            name='razlog_prijave',
            field=models.CharField(max_length=64),
        ),
    ]
