# Generated by Django 3.0.5 on 2020-05-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispitni_rokovi', '0018_auto_20200317_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ispitnirok',
            name='proveren',
            field=models.BooleanField(default=False),
        ),
    ]
