# Generated by Django 3.0.4 on 2020-03-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50)),
                ('naslov', models.CharField(max_length=255)),
                ('opis', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('hash_value', models.CharField(max_length=64)),
                ('datum', models.DateTimeField()),
            ],
        ),
    ]
