# Generated by Django 3.1.2 on 2020-10-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_ac_rs_updates', '0002_auto_20200401_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novost',
            name='naslov',
            field=models.CharField(max_length=8192),
        ),
        migrations.AlterField(
            model_name='novost',
            name='opis',
            field=models.CharField(max_length=8192),
        ),
    ]
