# Generated by Django 3.1.2 on 2020-10-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_ac_rs_updates', '0003_auto_20201023_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('uredjaj', models.CharField(max_length=255)),
                ('pretplate', models.TextField(default='')),
            ],
        ),
    ]
