# Generated by Django 3.1.2 on 2020-11-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_ac_rs_updates', '0006_auto_20201026_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='departmani',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='smerovi',
            field=models.TextField(default=''),
        ),
    ]
