# Generated by Django 3.1.2 on 2020-11-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_ac_rs_updates', '0008_auto_20201110_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='smerovi_departmani',
            new_name='departmani',
        ),
        migrations.AddField(
            model_name='student',
            name='smerovi',
            field=models.TextField(default=''),
        ),
    ]
